In [ ]:
import nltk
# nltk.download('all')
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer

**Load Dataset**

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/Nlp Dev/dataset.csv')
data.head()

Unnamed: 0                                        source_text  \
0           0  Researchers have discovered a new species of b...   
1           1  The moon orbits the Earth in approximately 27....   
2           2  Water is composed of two hydrogen atoms and on...   
3           3          The history of Rome dates back to 753 BC.   
4           4  Pluto was once considered the ninth planet in ...   

                                    plagiarized_text  label  
0  Scientists have found a previously unknown but...      1  
1  Our natural satellite takes around 27.3 days t...      1  
2  H2O consists of 2 hydrogen atoms and 1 oxygen ...      1  
3  Rome has a long history that can be traced bac...      1  
4  In the past, Pluto was classified as the ninth...      1

In [ ]:
data.shape

(370, 4)

In [ ]:
# clean Text

In [ ]:
data['label'].value_counts()

label
0    187
1    183
Name: count, dtype: int64

In [ ]:
import string
from nltk.corpus import stopwords
import nltk

# Make sure to download stopwords once
nltk.download('stopwords')

def processing_text(text):
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Convert to lowercase
    text = text.lower()
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    text = " ".join(word for word in text.split() if word not in stop_words)

    return text

print(processing_text('this is my %$&!text to use for dummy text'))

text use dummy text


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
data['source_text']=data['source_text'].apply(processing_text)

In [ ]:
data['plagiarized_text']=data['plagiarized_text'].apply(processing_text)

In [ ]:
data

Unnamed: 0                                        source_text  \
0             0  researchers discovered new species butterfly a...   
1             1           moon orbits earth approximately 273 days   
2             2  water composed two hydrogen atoms one oxygen atom   
3             3                     history rome dates back 753 bc   
4             4         pluto considered ninth planet solar system   
..          ...                                                ...   
365         397    playing musical instruments enhances creativity   
366         398       studying history helps understanding present   
367         399            listening classical music improve focus   
368         400      practicing yoga enhances physical flexibility   
369         401              volunteering fosters community spirit   

                                      plagiarized_text  label  
0    scientists found previously unknown butterfly ...      1  
1    natural satellite takes around 273 days comple...      1  
2          h2o consists 2 hydrogen atoms 1 oxygen atom      1  
3                 rome long history traced back 753 bc      1  
4    past pluto classified ninth planet suns planet...      1  
..                                                 ...    ...  
365    creativity enhanced playing musical instruments      0  
366       understanding present aided studying history      0  
367           focus improved listening classical music      0  
368      physical flexibility enhanced practicing yoga      0  
369             community spirit fostered volunteering      0  

[370 rows x 4 columns]

In [ ]:
# TfidfVectorizer

In [ ]:
tfidf=TfidfVectorizer()
x=tfidf.fit_transform(data['source_text']+" "+data['plagiarized_text'])

In [ ]:

y = data['label']

print(x)
print(y)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2152 stored elements and shape (370, 1112)>
  Coords	Values
  (0, 854)	0.23991410374904304
  (0, 293)	0.23991410374904304
  (0, 672)	0.18646903930972664
  (0, 938)	0.44856484895246024
  (0, 142)	0.4798282074980861
  (0, 53)	0.3483837261559235
  (0, 815)	0.19161700361200087
  (0, 892)	0.23991410374904304
  (0, 414)	0.17419186307796175
  (0, 779)	0.23991410374904304
  (0, 1050)	0.23991410374904304
  (0, 545)	0.23991410374904304
  (1, 647)	0.18617822331065687
  (1, 703)	0.23310447789701255
  (1, 309)	0.15762982348385968
  (1, 66)	0.18617822331065687
  (1, 12)	0.4662089557940251
  (1, 267)	0.43583296389857457
  (1, 661)	0.18617822331065687
  (1, 886)	0.23310447789701255
  (1, 993)	0.21791648194928728
  (1, 72)	0.38390486276730146
  (1, 213)	0.23310447789701255
  (1, 695)	0.1811763767657395
  (1, 702)	0.21791648194928728
  :	:
  (365, 659)	0.4928093977943177
  (365, 526)	0.5184467929434351
  (366, 490)	0.41873273286716306
  (366,

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
accuracy_score=accuracy_score(y_test,y_pred)
accuracy_score
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.86      0.82        35
           1       0.86      0.79      0.83        39

    accuracy                           0.82        74
   macro avg       0.83      0.83      0.82        74
weighted avg       0.83      0.82      0.82        74

[[30  5]
 [ 8 31]]


In [ ]:
print(confusion_matrix(y_test,y_pred))

[[30  5]
 [ 8 31]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Instantiate the model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model
model.fit(x_train, y_train)

# Make predictions
y_pred = model.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Generate classification report
classification_rep = classification_report(y_test, y_pred)

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_rep)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.7972972972972973
Classification Report:
              precision    recall  f1-score   support

           0       0.71      0.97      0.82        35
           1       0.96      0.64      0.77        39

    accuracy                           0.80        74
   macro avg       0.83      0.81      0.79        74
weighted avg       0.84      0.80      0.79        74

Confusion Matrix:
[[34  1]
 [14 25]]


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Instantiate the model
model = SVC(kernel='linear', random_state=42)

# Fit the model
model.fit(x_train, y_train)

# Make predictions
y_pred = model.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Generate classification report
classification_rep = classification_report(y_test, y_pred)

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print results
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_rep)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.8783783783783784
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.89      0.87        35
           1       0.89      0.87      0.88        39

    accuracy                           0.88        74
   macro avg       0.88      0.88      0.88        74
weighted avg       0.88      0.88      0.88        74

Confusion Matrix:
[[31  4]
 [ 5 34]]


In [ ]:
# save SVM and Vectorizr

In [ ]:
import pickle

pickle.dump(model,open("model.pkl",'wb'))
pickle.dump(tfidf, open('tfidf.pkl','wb'))

In [ ]:
# load model and vectorizer

In [ ]:
model = pickle.load(open('model.pkl','rb'))
tfidf = pickle.load(open('tfidf.pkl','rb'))

In [ ]:
# Detection System

In [ ]:
def detect(input_text):
    vectorized_text = tfidf.transform([input_text])
    result = model.predict(vectorized_text)
    return "Plagiarim Detected" if result[0] == 1 else "No Plagiarism"

In [ ]:
# example ( it is a plagarized text)
input_text = 'Researchers have discovered a new species of butterfly in the Amazon rainforest.'
detect(input_text)

'Plagiarim Detected'